apiVersion: v1
kin: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    name: busy
    command:
      - sleep
      - "3600"
# caminho montado no Pod do Empty dir, ele inicia vazio, junto com o pod
    volumeMounts:
    - mountPath: /giropops
    - name: giropops-dir
  volumes:
  - name: giropops-dir
    emptyDir: {}
