apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-com-configmap
  name: pod-com-configmap
spec:
  containers:
  - image: busybox
    name: pod-com-configmap
    command:
      - sleep
      - "3600"
    env:
    - name: frutas
      valueFrom: #pega o valor de uma configMap chamada cores-frutas com a Key: predileta
        configMapKeyRef:
          name: cores-frutas
          key: predileta
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
