apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-com-configmap
  name: pod-com-configmap
spec:
  containers:
  - image: busybox
    name: pod-com-configmap
    command:
      - sleep
      - "3600"
    envFrom:
    - configMapRef:
        name: cores-frutas
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
