apiVersion: v1
kind: LimitRange
metadata:
  name: limited-namespace
spec:
  limits:
  - default:
      cpu: 1
      memory: 256Mi
    defaultRequest:
      cpu: 0.5
      memory: 128Mi
    type: Container #Tipo de recurso que será afetado pela limitação de recursos
