{
 "title": "Aplicaçoes-v2",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "type": "table",
   "description": "A query D teve como base a query do dashboard de aplicações utilizado anteriormente, pode ser melhorado conforme aprovação",
   "gridPos": { "h": 28, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", image!=\"\", container!=\"\",container!=\"migrate-clj-job\", container!=\"kubectl-migrate\"}[$__rate_interval])) by (container) / sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", resource=\"cpu\",container!=\"migrate-clj-job\", container!=\"\", container!=\"kubectl-migrate\"}) by (container) "
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", image!=\"\", container!=\"migrate-clj-job\", container!=\"\", container!=\"kubectl-migrate\"}) by (container) / sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",  resource=\"memory\", container!=\"migrate-clj-job\", container!=\"\", container!=\"kubectl-migrate\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\",container!=\"POD\",container!=\"migrate-clj-job\",container!=\"kubectl-migrate\",container!=\"\"}) by (container)"
    },
    {
     "expr": "max(increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",container!=\"migrate-clj-job\",container!=\"kubectl-migrate\"}[1h])) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\",container!=\"POD\",container!=\"migrate-clj-job\",container!=\"kubectl-migrate\",container!=\"\"}) by (container)"
    },
    {
     "expr": "time() - kube_pod_container_state_started{namespace=~\"$namespace\",container!=\"migrate-clj-job\",container!=\"kubectl-migrate\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 0 },
   "options": {
    "content": "<h4 style=\"text-align: center; font-size: 80px; color: LimeGreen;\"><strong>${datasource}</strong></h4>\r\n\r\n"
   }
  },
  {
   "title": "CPU Core ",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (machine_cpu_cores)", "legendFormat": "Total CPU cores" },
    {
     "expr": "sum(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Usage amount"
    }
   ]
  },
  {
   "title": "Node memory ",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(machine_memory_bytes)", "legendFormat": "Total memory" },
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)",
     "legendFormat": "Usage amount"
    }
   ]
  },
  {
   "title": "Node storage (contain. fs)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint=\"/\" })",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", mountpoint=\"/\" }) - sum(node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"\",mountpoint=\"/\" })",
     "legendFormat": "Usage amount"
    }
   ]
  },
  {
   "title": "Total Pod Restarts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",container!=\"migrate-clj-job\",container!=\"kubectl-migrate\"}[1h]))) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NODES",
   "type": "table",
   "gridPos": { "h": 18, "w": 11, "x": 13, "y": 10 },
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "{{node}}" },
    {
     "expr": " (count by (node)(container_spec_memory_reservation_limit_bytes{pod!=\"\"}))"
    },
    {
     "expr": "((label_replace((node_memory_MemTotal_bytes  + on(instance) group_left(nodename) \nnode_uname_info),\"node\",\"$1\",\"nodename\", \"(.+)\"))  -  (label_replace((node_memory_MemAvailable_bytes  + on(instance) group_left(nodename) \nnode_uname_info),\"node\",\"$1\",\"nodename\", \"(.+)\"))) /  (label_replace((node_memory_MemTotal_bytes  + on(instance) group_left(nodename) \nnode_uname_info),\"node\",\"$1\",\"nodename\", \"(.+)\")) "
    },
    {
     "expr": "sum by (node)(label_replace(instance:node_cpu:ratio + on(instance) group_left(nodename) \nnode_uname_info,\"node\",\"$1\",\"nodename\", \"(.+)\") ) / sum by (node)(kube_node_status_capacity{resource=\"cpu\"})"
    },
    { "expr": "kube_node_role" },
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\"}) by (node) / sum(avg(container_fs_limit_bytes{device=~\"^/dev/.*$\"})by (node)) by (node) "
    }
   ]
  }
 ]
}