{
 "title": "logging-api",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{namespace=~\"$namespace\"},container)"
    }
   },
   {
    "name": "output",
    "query": {}
   },
   { "name": "query" }
  ]
 },
 "panels": [
  {
   "title": "Visão geral",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", container=~\"$container\", resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", container=~\"$container\", resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=~\"$container\", image!=\"\", container!=\"\"}[$__rate_interval])) by (pod) / sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", container=~\"$container\", resource=\"cpu\"}) by (pod) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", container=~\"$container\", image!=\"\", container!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", container=~\"$container\", resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=~\"$container\", image!=\"\", container!=\"\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", container=~\"$container\", image!=\"\", container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"$namespace\", container=~\"$container\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Success Logs - $query",
   "type": "logs",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{container=~\"$container\", stream=~\"$output\"} | regexp \"(?P<log>\\\\{.*)\"|=\"{\" |line_format \"{{.log}}\"|=\"$query\""
    }
   ]
  },
  {
   "title": "Status Count",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({container=~\"$container\", stream=~\"$output\"} |= `:status` | regexp `(?P<status>\\:status \\d{3})` | line_format `{{.status}}` [$__range])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Logs - ERRORS",
   "type": "logs",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{container=~\"$container\", stream=~\"$output\"} |~ \"(ERROR)\" "
    }
   ]
  },
  {
   "title": "Query string null",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 1 }
   ]
  },
  {
   "title": "Error Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 40 }
   ]
  }
 ]
}