{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "resolution",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "datacenter",
    "query": {
     "query": "label_values(cassandra_table_totaldiskspaceused_count{cluster=\"$cluster\"}, datacenter)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(cassandra_table_totaldiskspaceused_count, cluster)"
    }
   },
   {
    "name": "keyspace",
    "query": {
     "query": "label_values(cassandra_table_totaldiskspaceused_count{datacenter=\"$datacenter\", cluster=\"$cluster\"}, keyspace)"
    }
   },
   {
    "name": "table",
    "query": {
     "query": "label_values(cassandra_table_totaldiskspaceused_count{datacenter=\"$datacenter\", cluster=\"$cluster\", keyspace=\"$keyspace\"}, table)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(cassandra_table_totaldiskspaceused_count{datacenter=\"$datacenter\", cluster=\"$cluster\",}, instance)"
    }
   },
   { "name": "interval", "query": "1m" },
   {
    "name": "broker",
    "label": "Broker",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_controllerstate{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_cluster_partition_replicascount{job=\"$job\"}, topic)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_controllerstate, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Dev-seg", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cassandra",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kafka",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kubernetes",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 8, "x": 14, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Used by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (cassandra_keyspace_totaldiskspaceused{datacenter=\"$datacenter\", cluster=\"$cluster\", instance=~\"$instance\"})",
     "legendFormat": "{{ instance }} - used"
    }
   ]
  },
  {
   "title": "Disk used by kafka",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort(sum(kafka_log_size{job=\"$job\",instance=~\"$broker\"})by(instance))",
     "legendFormat": "Instance Broker:  {{instance}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} - node_memory_MemAvailable_bytes{job=\"node-exporter\"})",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"byte\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"byte\"})",
     "legendFormat": "Limits"
    },
    { "expr": "sum(machine_memory_bytes)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(1-rate(node_cpu_seconds_total{mode=\"idle\", job=\"node-exporter\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unit=\"core\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unit=\"core\"})",
     "legendFormat": "Limits"
    },
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "CPU Utilization by instance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\", job=\"node-exporter\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance)(jvm_memory_bytes_used{datacenter=\"$datacenter\", cluster=\"$cluster\", area=\"heap\" ,job=\"cassandra_discovery\"}) + sum by (instance)(jvm_memory_bytes_used{datacenter=\"$datacenter\", cluster=\"$cluster\", area=\"nonheap\" ,job=\"cassandra_discovery\"})",
     "legendFormat": "{{ instance }} - used"
    },
    {
     "expr": "sum by (instance)(jvm_memory_bytes_max{datacenter=\"$datacenter\", cluster=\"$cluster\", area=\"heap\" ,job=\"cassandra_discovery\"})",
     "legendFormat": "{{instance}} - max"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance)(jvm_memory_bytes_used{datacenter=\"$datacenter\", cluster=\"$cluster\", area=\"heap\" ,job=\"kafka_discovery\"}) + sum by (instance)(jvm_memory_bytes_used{datacenter=\"$datacenter\", cluster=\"$cluster\", area=\"nonheap\" ,job=\"kafka_discovery\"})",
     "legendFormat": "{{ instance }} - used"
    },
    {
     "expr": "sum by (instance)(jvm_memory_bytes_max{datacenter=\"$datacenter\", cluster=\"$cluster\", area=\"heap\" ,job=\"kafka_discovery\"})",
     "legendFormat": "{{instance}} - max"
    }
   ]
  },
  {
   "title": "Memory Utilization by instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"node-exporter\"} - node_memory_MemAvailable_bytes{job=\"node-exporter\"}) by (instance)",
     "legendFormat": "{{ node}}"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"node-exporter\"}) by (instance)",
     "legendFormat": "{{instance}}-TOTAL"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance!=\"\", job=\"cassandra_discovery\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"$job\",topic=\"\"}[1m]))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount)"
    }
   ]
  },
  {
   "title": "Total of Topics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount{job=~\"$job\"})"
    }
   ]
  }
 ]
}