version: "3.8"
services:
  coqui_tts:
    build: .
    container_name: kokoro_tts
    volumes:
      - ./output:/app/output
      - ./synthesize.py:/app/synthesize.py
#      - ./.local:/root/.local
      - ./1-teste.txt:/app/1-teste.txt
      - ./2-teste.txt:/app/2-teste.txt
    command: >
      sh -c "python synthesize.py 1-teste.txt"
