---
- name: Install python in target node with ansible
  hosts: deb-based
  become: true
  gather_facts: no
  pre_tasks:
  - name: install python
    raw: ' apt install python3 -y '
    args:
      executable: /bin/bash