---
- name: Create ansible user and copy key generate for setup.sh
  hosts: deb-based
  become: true
  gather_facts: no
  pre_tasks:
  - name: Create a user ansible in ~ansible/
    ansible.builtin.user:
      name: ansible
      groups: sudo
      shell: /bin/bash
  - name: ansible create directory .ssh
    file:
      path: /home/ansible/.ssh
      state: directory
  - name: ensure private key and public one are present
    copy: 
      src: id_rsa.pub 
      dest: "/home/ansible/.ssh/{{ item }}" 
      owner: ansible
      group: ansible
      mode: 0600
    with_items:
      - authorized_keys
  - name: Disable Password Authentication
    lineinfile:
           dest: /etc/ssh/sshd_config
           regexp: '^PasswordAuthentication'
           line: "PasswordAuthentication no"
           state: present
           backup: yes
  - name: Disable Root Login
    lineinfile:
           dest: /etc/ssh/sshd_config
           regexp: '^PermitRootLogin'
           line: "PermitRootLogin no"
           state: present
           backup: yes
  - name: Disable sudo password obrigatority
    lineinfile:
           dest: /etc/sudoers
           line: "ansible ALL=(ALL) NOPASSWD: ALL"
           backup: yes
  - name: restart ssh
    service:
      name: sshd
      state: restarted