version: "3"

services:

  ubuntu:
    image: ubuntu
    hostname: ubuntu
    networks:
      - ansible
    entrypoint: ["watch","./"]
  debian:
    image: debian
    hostname: debian
    networks:
      - ansible
    entrypoint: ["watch","./"]
  arch:
    image: archlinux
    hostname: arch
    networks:
      - ansible
    entrypoint: ["watch","./"]
networks:
  ansible:
    driver: bridge
